Cxc 421 catalog does not look good when there is no search result
comixcraft/Editor pull request #98
Opened 2024-06-01 12:39 UTC by AntoinouM

Have a look if in your opinion the text size of text is too big for the desktop version.

2024-06-02 17:05 UTC, hollaa commented
I think it would be better to use h3 tag instead of the h1 although its not consistent, it looks better. And then on mobile it would be great if it could be centred, but thats just my suggestion. Other than that, I think its great!

2024-06-02 17:06 UTC, hollaa requested changes
I think it would be better to use h3 tag instead of the h1 although its not consistent, it looks better. And then on mobile it would be great if it could be centred, but thats just my suggestion. Other than that, I think its great!

2024-06-03 13:16 UTC, AntoinouM commented
Changed it

2024-06-03 13:21 UTC, hollaa approved these changes

2024-06-03 15:29 UTC, merged